export const ADD_ELEMENT = "ADD_ELEMENT";
export const ADD_ELEMENTS = "ADD_ELEMENTS";
export const DELETE_ELEMENTS = "DELETE_ELEMENTS";
export const ADD_ELEMENT_TO_SELECTION = "ADD_ELEMENT_TO_SELECTION";
export const ADD_ELEMENTS_TO_SELECTION = "ADD_ELEMENTS_TO_SELECTION";
export const UNSELECT_ALL_ELEMENTS = "UNSELECT_ALL_ELEMENTS";
export const COPY_SELECTION = "COPY_SELECTION";
export const SET_SELECT_VALUE = "SET_SELECT_VALUE";
export const SET_INPUT_VALUE = "SET_INPUT_VALUE";
export const ADD_LINK = "ADD_LINK";
export const DELETE_LINK = "DELETE_LINK";
export const MOVE_ELEMENTS = "MOVE_ELEMENTS";
export const CLEAR_ELEMENTS = "CLEAR_ELEMENTS";
export const RESIZE_ELEMENT = "RESIZE_ELEMENT";
export const OPEN_WORKFLOW = "OPEN_WORKFLOW";
export const UPDATE_DATA_IN_DATA_ELEMENT = "UPDATE_DATA_IN_DATA_ELEMENT";

export const CHANGE_ZOOM = "CHANGE_ZOOM";
